Fix the argument mismatch in ``_lsprof`` for ``PY_THROW`` event.
